In [11]:
!pip install xgboost

In [35]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [3]:
cd ./drive/MyDrive/미니_프로젝트/etc/final

/content/drive/MyDrive/미니_프로젝트/etc/final


# 모든 feature가 다 포함

In [41]:
train_fast = pd.read_csv('./train_fast_all.csv')
test_fast = pd.read_csv('./test_fast_all.csv')
train_slow = pd.read_csv('./train_slow_all.csv')
test_slow = pd.read_csv('./test_slow_all.csv')

In [16]:
train_fast.shape, test_fast.shape, train_slow.shape, test_slow.shape

((102316, 68), (25575, 68), (102294, 68), (25575, 68))

## 급속 충전기

In [42]:
X_fast_train = train_fast.drop(['fast_exist'], axis=1)
y_fast_train = train_fast.fast_exist

X_fast_test = test_fast.drop(['fast_exist'], axis=1)
y_fast_test = test_fast.fast_exist

In [48]:
RF = RandomForestClassifier(random_state=42)

In [49]:
RF.fit(X_fast_train, y_fast_train)

RandomForestClassifier(random_state=42)

In [50]:
y_fast_pred = RF.predict(X_fast_test)

In [51]:
confusion_matrix(y_fast_test, y_fast_pred)

array([[25545,     5],
       [   10,    15]])

In [52]:
f1_score(y_fast_test, y_fast_pred)

0.6666666666666665

In [43]:
XGB = XGBClassifier(random_state=42)

In [44]:
XGB.fit(X_fast_train, y_fast_train)

XGBClassifier(random_state=42)

In [45]:
y_fast_pred = XGB.predict(X_fast_test)

In [46]:
confusion_matrix(y_fast_test, y_fast_pred)

array([[25465,    85],
       [    5,    20]])

In [47]:
f1_score(y_fast_test, y_fast_pred)

0.3076923076923077

## 완속 충전기

In [53]:
X_slow_train = train_slow.drop(['slow_exist'], axis=1)
y_slow_train = train_slow.slow_exist

X_slow_test = test_slow.drop(['slow_exist'], axis=1)
y_slow_test = test_slow.slow_exist

In [54]:
RF = RandomForestClassifier(random_state=42)

In [55]:
RF.fit(X_slow_train, y_slow_train)

RandomForestClassifier(random_state=42)

In [56]:
y_slow_pred = RF.predict(X_slow_test)

In [57]:
confusion_matrix(y_slow_test, y_slow_pred)

array([[25545,     0],
       [   30,     0]])

In [58]:
f1_score(y_slow_test, y_slow_pred)

0.0

In [59]:
XGB = XGBClassifier(random_state=42)

In [60]:
XGB.fit(X_slow_train, y_slow_train)

XGBClassifier(random_state=42)

In [61]:
y_slow_pred = XGB.predict(X_slow_test)

In [62]:
confusion_matrix(y_slow_test, y_slow_pred)

array([[25545,     0],
       [   30,     0]])

In [63]:
f1_score(y_slow_test, y_slow_pred)

0.0